#!/bin/bash

PKG="${1}"

if [ $(dpkg-query -W -f='${Status}' ${PKG} 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  echo "installing '${PKG}'..."
  sudo apt install ${PKG} -y
else
  echo "'${PKG}' already installed..."
fi